// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  'aws_project_region': 'us-east-1',
  'aws_cognito_identity_pool_id': 'us-east-1:e1d908df-57f8-4420-8ff8-be581de10f14',
  'aws_cognito_region': 'us-east-1',
  'aws_user_pools_id': 'us-east-1_qkrReJEXS',
  'aws_user_pools_web_client_id': '6mf5udels1t77e7mdg6h2ba08n',
  'oauth': {},
  'aws_appsync_graphqlEndpoint': 'https://qp5i5w2xa5asbes3wtb7os7iky.appsync-api.us-east-1.amazonaws.com/graphql',
  'aws_appsync_region': 'us-east-1',
  'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
  'aws_content_delivery_bucket': 'agent0-quasar-bucket-dev',
  'aws_content_delivery_bucket_region': 'us-east-1',
  'aws_content_delivery_url': 'https://d1ubdss5zw2zg9.cloudfront.net'
}

export default awsmobile
